### ISSUE TITLE
Binding with innerHTML didn't fire script tag

### ISSUE THREAD

**Issue by jedireza** [AmpersandJS/ampersand-dom-bindings#11]
Possible edge case here :wink: 

We were getting a Tweet's embed code form the Twitter API which sends back some HTML you can put in your page. When we using the `innerHTML` binding with a view, the HTML was placed as expected, but the script tag contained in the HTML didn't fire.

Example HTML sent back from Twitter:

```html
<blockquote class="twitter-tweet" align="center" width="350">
<p>From Madrid to the Int&#39;l Space Station, eyes turn to the Supermoon on Sunday - PHOTOS: <a href="http://t.co/HJ25f9KrUV">http://t.co/HJ25f9KrUV</a> <a href="http://t.co/Om3ujf4ldn">pic.twitter.com/Om3ujf4ldn</a></p>&mdash; ABC News (@ABC) <a href="https://twitter.com/ABC/statuses/499065279360430080">August 12, 2014</a>
</blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

I ended up creating a `session` property on the view and `listeningTo` it for changes, and then setting the HTML content with jQuery via `$(...).html(...)`, which worked.

I quickly checked the source in this repo and in `ampersand-dom` and didn't see anything that would cause this. Maybe I missed it.

**Comment by HenrikJoreteg** [comment]
i'm ok with this not working out of the box as loading scripts is something that we want to encourage people to do explicitly as part of their application not within templates. Plus, we're simply following security model created by the browser.
