### ISSUE TITLE
Attribute `indeterminate` is not correctly toggled

### ISSUE THREAD

**Issue by bryanspears** [AmpersandJS/ampersand-dom-bindings#38]
```
'model.checkAllState': {
	type: 'switchAttribute',
	selector: '[data-hook=check_all] input[type=checkbox]',
	cases: {
		checked: {checked: null},
		unchecked: {},
		indeterminate: {indeterminate: null}
	}
}
```

It correctly adds the `indeterminate` attribute to the input checkbox, however, it seems you must use javascript to set the property `el.indeterminate = true` otherwise it does not correctly trigger indeterminate state. Does ampersand need some notion of attribute vs. property (like jquery does with .prop and .attr)?

Obvious workaround (and what I've done) is a custom binding function, but it be nice to have the above working correctly to keep the code succinct. 

For anyone curious. Here's my custom model and binding:
```
session: {
	checkAllState: {
		type: 'string',
		values: ['checked', 'indeterminate', 'unchecked'],
		default: 'unchecked'
	}
}

'model.checkAllState': {
	selector: '[data-hook=check_all] input[type=checkbox]',
	type: function (el, value, previousValue) {
		if (value === 'indeterminate') {
			el.indeterminate = true;
			el.checked = false;
		} else if (value === 'unchecked') {
			el.indeterminate = false;
			el.checked = false
		} else if (value === 'checked') {
			el.indeterminate = false;
			el.checked = true;
		}
	}
}
```

Tested in the latest version of Chrome.

**Comment by pgilad** [comment]
Hey, thanks for the issue. This modules uses the dom `setAttribute` in order to set attributes (see https://github.com/AmpersandJS/ampersand-dom-bindings/blob/2e4f85701dc0d826ae17116b4270c508cf0fc94f/ampersand-dom-bindings.js#L47)

Can you isolate this and make sure this is indeed the issue? Are there any better workarounds to setting properties/attributes?

**Comment by bryanspears** [comment]
Yeah. I'll definitely look into it some more. I'm pretty sure my past self was in the woes of learning ampersand at the time and didn't realize there might have been another way to accomplish this. I'll try to get back tomorrow on this.

**Comment by bryanspears** [comment]
I guess this is more a problem with ampersand-dom. I tried `el.setAttribute('indeterminate', true);` and that failed. It's an actual JS property. Jquery's `prop()` method works due to their implementation `el[name] = value` which is what ampersand would have to do to support this.

Guess I'll report my issue over there.
