### ISSUE TITLE
class attribute via DOM binding to append itself to existing classes and not overwrite all

### ISSUE THREAD

**Issue by orenmizr** [AmpersandJS/ampersand-dom-bindings#46]
```
bindings: {
    "model.name": {
      type: 'attribute',
      hook: 'tabIcon',
      name: 'class'
    }
  }
```
this will make DIV.tab.tab__1 --> DIV.icon and not DIV.tab.tab__1.icon

is it possible to achieve that?

**Comment by pgilad** [comment]
If you want to toggle a dynamic class you should use:
https://github.com/AmpersandJS/ampersand-dom-bindings#class

If you want to toggle a static boolean class, you should use:
https://github.com/AmpersandJS/ampersand-dom-bindings#booleanclass

`attribute` is the wrong binding to use here.
